name: build

on:
  push:
env:
  PAWPAW_SKIP_LV2: 1

jobs:
  linux-standalone:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04

    permissions:
        contents: write

    container:
      image: ubuntu:20.04
      options: --user root

    steps:
      - name: Prepare system
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update -qq
          apt-get install -yqq \
            tzdata \
            git ca-certificates build-essential \
            pkg-config curl wget unzip \
            software-properties-common

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -app
          lto: false
          pawpaw: true

  linux-clap:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04

    permissions:
        contents: write

    container:
      image: ubuntu:20.04
      options: --user root

    steps:
      - name: Prepare system
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update -qq
          apt-get install -yqq \
            tzdata \
            git ca-certificates build-essential \
            pkg-config curl wget unzip \
            software-properties-common

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -clap
          extraargs: clap
          lto: false
          pawpaw: true

  linux-vst2:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04

    permissions:
        contents: write

    container:
      image: ubuntu:20.04
      options: --user root

    steps:
      - name: Prepare system
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update -qq
          apt-get install -yqq \
            tzdata \
            git ca-certificates build-essential \
            pkg-config curl wget unzip \
            software-properties-common

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -vst2
          extraargs: vst2
          lto: false
          pawpaw: true

  windows-clap:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -clap
          extraargs: clap
          pawpaw: true

  windows-vst2:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -vst2
          extraargs: vst2
          pawpaw: true

  source:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: source

