name: build

on:
  push:
env:
  PAWPAW_SKIP_LV2: 1

jobs:
  linux-standalone:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:20.04

    permissions:
        contents: write

    steps:
      - name: Install git inside container
        run: |
          apt-get update
          apt-get install -y git libc-bin

      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -app
          lto: false
          pawpaw: true

  linux-clap:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:20.04

    permissions:
        contents: write

    steps:
      - name: Install git inside container
        run: |
          apt-get update
          apt-get install -y git libc-bin

      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -clap
          extraargs: clap
          lto: false
          pawpaw: true

  linux-vst2:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:20.04

    permissions:
        contents: write

    steps:
      - name: Install git inside container
        run: |
          apt-get update
          apt-get install -y git libc-bin

      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -vst2
          extraargs: vst2
          lto: false
          pawpaw: true

  windows-clap:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -clap
          extraargs: clap
          pawpaw: true

  windows-vst2:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -vst2
          extraargs: vst2
          pawpaw: true

  source:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: source

