name: build

on:
  push:
env:
  PAWPAW_SKIP_LV2: 1

jobs:
  linux-standalone:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -app
          lto: false
          pawpaw: true

  linux-clap:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -clap
          extraargs: clap
          lto: false
          pawpaw: true

  windows-clap:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -clap
          extraargs: clap
          pawpaw: true

  source:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: source

